[build]
  publish = "parenting-frontend"  # 指向前端文件夹

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "netlify/functions"

# SPA 支持，确保路由正确
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
